### ISSUE TITLE
强哥，你目前在日本那边跳槽了吗？跳槽了的话，可以帮我内推一下你前面一份工作吗？

### ISSUE THREAD

**Issue by JackRo** [Thewhitelight/ExcursionsAndriod#2]
强哥，你目前在日本那边跳槽了吗？跳槽了的话，可以帮我内推一下你前面一份工作吗？ :worried:

**Comment by Thewhitelight** [comment]
> 强哥，你目前在日本那边跳槽了吗？跳槽了的话，可以帮我内推一下你前面一份工作吗？ :worried:

你给我邮箱丢个简历
